### ISSUE TITLE
Cannot Finish the quiz

### ISSUE THREAD

**Issue by sahilbadyal** [appteam-nith/Hillffair#127]
If the time runs out during the quiz, one cannot finish the quiz as nothing happens if we click on finish the quiz

**Comment by sahilbadyal** [comment]
How to recreate? 
Start the quiz 
Let the time run out 
Now click on finish quiz 
Nothing happens

**Comment by sukhbir-singh** [comment]
Sir when time runs out and your device is connected to internet then quiz gets automatically submitted.
