### ISSUE TITLE
Transitions needed between activities

### ISSUE THREAD

**Issue by sukhbir-singh** [appteam-nith/Hillffair#63]
Suitable transition is required to be added to app between activities

**Comment by joshafest** [comment]
Could you please elobrate it?
what do you mean ?... you need transactions of points?..... like transaction of money send receive ?

**Comment by sukhbir-singh** [comment]
See https://developer.android.com/training/transitions/transitions.html#Create

**Comment by joshafest** [comment]
pull #128

**Comment by joshafest** [comment]
Ofcourse it can be improved, but it the way "How to do it" 
probably my last work on gui, What i wanted for hillffair was use of cryptography and blockchain based system for rewards gaining points by quiz. But no one seems to be intrested from respected sirs,
