### ISSUE TITLE
App crashes during signup

### ISSUE THREAD

**Issue by joshafest** [appteam-nith/Hillffair#69]
When any of 
isName , isemail ,ispassword , isphone

Get true under "if " condition 'SignupActivity.java' 
The app crashes during the filling of form.

**Comment by sukhbir-singh** [comment]
Please again check on latest repo

**Comment by joshafest** [comment]
Where it is? I am pretty sure that I have used master branch.

**Comment by joshafest** [comment]
You just commited ..let me have a look,

**Comment by joshafest** [comment]
Done, it was due to missing local Maven Android support library version 28 revision 38
