### ISSUE TITLE
Login screen layout doesn't fits in small screen sizes.

### ISSUE THREAD

**Issue by adi23arora** [appteam-nith/Hillffair#85]
The Signup part on the login screen is not visible on screens with sizes 4.5 inches & less.
Either it should be added inside a scroll view or it can be replaced with a button, below the login button.

**Comment by sukhbir-singh** [comment]
@adi23arora Please post screenshots also.

**Comment by adi23arora** [comment]
![screenshot_2016-10-14-03-40-51](https://cloud.githubusercontent.com/assets/17095968/19378190/e5fd648a-9208-11e6-8aa9-b3168c843d9c.png)

**Comment by joshafest** [comment]
@sukhbir-singh , sir should I look to fix it ?

**Comment by sukhbir-singh** [comment]
ofcourse, @joshafest  fix this and close this issue
